name: build-site

on:
  push:
    branches:
      - main
      - master

jobs:
  targets:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build development environment
        run: |
          nix-build

      - name: Install Hugo from deb package
        run: |
          sudo dpkg -i hugo_0.25.1_Linux-64bit.deb

      - name: Build site
        run: |
          nix-shell default.nix --run "Rscript -e 'blogdown::build_site(build_rmd = TRUE)'"         

      - name: Upload latest run
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add public/
          git commit -am "Updated blog"
          git push origin master
